name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::211125750247:role/github-actions-Anderson0933-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "anderson0933-sa-east-1-terrafome-statefile"
      aws-lock-dynamodb-table: "anderson0933-sa-east-1-terraform-lock"